In [2]:
import numpy as np
import matplotlib.pyplot as plt
import exact_cover 

In [3]:
#AC:
DTYPE = exact_cover.io.DTYPE_FOR_ARRAY
RAW_SHAPES = {
    "F": [[1, 1, 0], [0, 1, 1], [0, 1, 0]],
    "I": [[1, 1, 1, 1, 1]],
    "L": [[1, 0, 0, 0], [1, 1, 1, 1]],
    "N": [[1, 1, 0, 0], [0, 1, 1, 1]],
    "P": [[1, 1, 1], [1, 1, 0]],
    "T": [[1, 1, 1], [0, 1, 0], [0, 1, 0]],
    "U": [[1, 1, 1], [1, 0, 1]],
    "V": [[1, 1, 1], [1, 0, 0], [1, 0, 0]],
    "W": [[1, 0, 0], [1, 1, 0], [0, 1, 1]],
    "X": [[0, 1, 0], [1, 1, 1], [0, 1, 0]],
    "Y": [[0, 1, 0, 0], [1, 1, 1, 1]],
    "Z": [[1, 1, 0], [0, 1, 0], [0, 1, 1]],
}
PENTOMINOS = [np.array(shape, dtype=DTYPE) for shape in RAW_SHAPES.values()]

In [34]:
#AC
# Création de "all_shapes"

pieces = ["F", "I", "L", "N", "P", "T", "U", "V", "W", "X", "Y", "Z"]
all_shapes = {} # Contiendra pour chaque pièce, une liste de toutes les shapes différentes possibles
for piece in pieces:
    new_shape = np.array(RAW_SHAPES[piece])
    new_shape_transpose = new_shape.T
    all_shapes[piece] = [new_shape]
    if not np.array_equal(new_shape, new_shape_transpose):
        all_shapes[piece].append(new_shape_transpose)
    for _ in range(4): # ajout de toutes les rotations/ rotations de symétries
        new_shape = np.rot90(new_shape)
        new_shape_transpose = np.rot90(new_shape_transpose)
        if not any(np.array_equal(shape, new_shape) for shape in all_shapes[piece]): #si new_shape n'est pas identique à une déjà présente
            all_shapes[piece].append(new_shape)
        if not any(np.array_equal(shape, new_shape_transpose) for shape in all_shapes[piece]): #si new_shape n'est pas identique à une déjà présente
            all_shapes[piece].append(new_shape_transpose)

all_shapes

{'F': [array([[1, 1, 0],
         [0, 1, 1],
         [0, 1, 0]]),
  array([[1, 0, 0],
         [1, 1, 1],
         [0, 1, 0]]),
  array([[0, 1, 0],
         [1, 1, 1],
         [1, 0, 0]]),
  array([[0, 1, 0],
         [0, 1, 1],
         [1, 1, 0]]),
  array([[0, 1, 0],
         [1, 1, 0],
         [0, 1, 1]]),
  array([[0, 1, 0],
         [1, 1, 1],
         [0, 0, 1]]),
  array([[0, 0, 1],
         [1, 1, 1],
         [0, 1, 0]]),
  array([[0, 1, 1],
         [1, 1, 0],
         [0, 1, 0]])],
 'I': [array([[1, 1, 1, 1, 1]]),
  array([[1],
         [1],
         [1],
         [1],
         [1]])],
 'L': [array([[1, 0, 0, 0],
         [1, 1, 1, 1]]),
  array([[1, 1],
         [0, 1],
         [0, 1],
         [0, 1]]),
  array([[0, 1],
         [0, 1],
         [0, 1],
         [1, 1]]),
  array([[1, 1, 1, 1],
         [1, 0, 0, 0]]),
  array([[1, 1, 1, 1],
         [0, 0, 0, 1]]),
  array([[1, 0],
         [1, 0],
         [1, 0],
         [1, 1]]),
  array([[1, 1],
         [1, 0],

In [ ]:
#ER



In [ ]:
#GP



In [ ]:
#TM



